apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "gateway.fullname" . }}
  labels:
    name: {{ include "gateway.fullname" . }}
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  # the port that this service should serve on
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.micro.nodePort }} # NodePort模式端口
  # label keys and values that must match in order to receive traffic for this service
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
